// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6AssignmentDarbyMecham.Models;

namespace Mission6AssignmentDarbyMecham.Migrations
{
    [DbContext(typeof(NewMovieContext))]
    [Migration("20230221160643_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6AssignmentDarbyMecham.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Miscellaneous"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Television"
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "VHS"
                        });
                });

            modelBuilder.Entity("Mission6AssignmentDarbyMecham.Models.NewMovie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieDirector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("newMovies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 8,
                            Edited = false,
                            LentTo = "Mom",
                            MovieDirector = "Jon M. Chu",
                            MovieRating = "PG-13",
                            MovieTitle = "Crazy Rich Asians",
                            MovieYear = "2018",
                            Notes = "None"
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 2,
                            Edited = false,
                            LentTo = "Chloe",
                            MovieDirector = "Michael McCullers",
                            MovieRating = "PG-13",
                            MovieTitle = "Baby Mama",
                            MovieYear = "2008",
                            Notes = "Funniest movie"
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 4,
                            Edited = false,
                            LentTo = "Adaly",
                            MovieDirector = "Jorge R. Gutierrez",
                            MovieRating = "PG",
                            MovieTitle = "Book of Life",
                            MovieYear = "2014",
                            Notes = "None"
                        });
                });

            modelBuilder.Entity("Mission6AssignmentDarbyMecham.Models.NewMovie", b =>
                {
                    b.HasOne("Mission6AssignmentDarbyMecham.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
