// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6AssignmentDarbyMecham.Models;

namespace Mission6AssignmentDarbyMecham.Migrations
{
    [DbContext(typeof(NewMovieContext))]
    partial class NewMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6AssignmentDarbyMecham.Models.NewMovie", b =>
                {
                    b.Property<string>("MovieTitle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieDirector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("MovieTitle");

                    b.ToTable("newMovies");

                    b.HasData(
                        new
                        {
                            MovieTitle = "Crazy Rich Asians",
                            Edited = false,
                            LentTo = "Mom",
                            MovieCategory = "Romantic Comedy",
                            MovieDirector = "Jon M. Chu",
                            MovieRating = "PG-13",
                            MovieYear = "2018",
                            Notes = "None"
                        },
                        new
                        {
                            MovieTitle = "Baby Mama",
                            Edited = false,
                            LentTo = "Chloe",
                            MovieCategory = "Comedy",
                            MovieDirector = "Michael McCullers",
                            MovieRating = "PG-13",
                            MovieYear = "2008",
                            Notes = "Funiest movie"
                        },
                        new
                        {
                            MovieTitle = "Book of Life",
                            Edited = false,
                            LentTo = "Adaly",
                            MovieCategory = "Childrens",
                            MovieDirector = "Jorge R. Gutierrez",
                            MovieRating = "PG",
                            MovieYear = "2014",
                            Notes = "None"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
